# Generated by Django 5.1.1 on 2024-10-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles', '0006_alter_detallepedido_pedido'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cantidad_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detalles.detallepedido'),
        ),
    ]
