# Generated by Django 5.1.1 on 2024-10-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_facturacion_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacion',
            old_name='cantidad_factura',
            new_name='cantidad',
        ),
    ]
