# Generated by Django 5.1.1 on 2024-10-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalles', '0004_alter_detallepedido_producto'),
        ('productos', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
