# Generated by Django 5.1.1 on 2024-10-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Pedido', models.CharField(max_length=100)),
                ('para_llevar', models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=10)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En preparación', 'En preparación'), ('Terminado', 'Terminado')], default='En espera', max_length=20)),
            ],
        ),
    ]
