# Generated by Django 5.1.1 on 2024-10-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pedido', models.CharField(max_length=100)),
                ('para_llevar', models.CharField(choices=[('No', 'NO'), ('Para llevar', 'Para llevar')], default='No', max_length=20)),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En preparación', 'En preparación'), ('Terminado', 'Terminado')], default='En espera', max_length=20)),
            ],
        ),
    ]
