# Generated by Django 5.1.1 on 2024-10-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_delete_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='para_llevar',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=20),
        ),
    ]
