# Generated by Django 5.1.1 on 2024-10-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles', '0002_alter_detallepedido_pedido'),
        ('pedido', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido'),
        ),
    ]
