# Generated by Django 5.1.1 on 2024-10-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles', '0005_alter_detallepedido_cantidad_and_more'),
        ('pedido', '0004_alter_pedido_para_llevar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido'),
        ),
    ]
